language: cpp

branches:
  only:
    - mangosr2-wotlk_ai

compiler:
  - gcc
  - clang

script:
  - test -d _build || mkdir _build
  - test -d _install || mkdir _install
  - cd _build
  - cmake -DPCH=1 -DCMAKE_INSTALL_PREFIX=../_install ..
  - make -j4
